### ISSUE TITLE
% лучше тоже отделять пробелами, ведь это также тип операции 

### ISSUE THREAD

**Issue by 3rOFd** [Kathrin-23/Work_2022_2#1]
https://github.com/Kathrin-23/Work_2022_2/blob/3a42b9b3419f3a70844a67372983d9d80f046747/LEC_3_3/main.cpp#L18

**Comment by Kathrin-23** [comment]
т.е. должно быть так : if (n % i == 0) ? 
Верно поняла?

**Comment by 3rOFd** [comment]
да)
