### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by DmitrTRC** [Kathrin-23/Work_2022_2#3]
https://github.com/Kathrin-23/Work_2022_2/blob/bd8ca2ffc90889adac7b975c58e82dba4be25c1a/HW_4_1/main.cpp#L1
* Translate to English. Something like this: "swap the maximum element  with the last negative element of the array [40]"

https://github.com/Kathrin-23/Work_2022_2/blob/bd8ca2ffc90889adac7b975c58e82dba4be25c1a/HW_4_1/main.cpp#L66
* Reformat code properly and delete empty lines 
* Delete unnecessary comments

https://github.com/Kathrin-23/Work_2022_2/blob/bd8ca2ffc90889adac7b975c58e82dba4be25c1a/HW_4_1/main.cpp#L21
- ### Here and until the end
* Add printf ("\n") for splitting output strings.
* Remove debug messages when the task is done
###  Change your logic!
 try to use initial values and variables for this problem something stuff like that:
    int max = array[0];
    int max_index = 0;
    int last_negative = array[0];
    int last_negative_index = 0;
And then make only the ONE LOOP iterations 
So after that, you have only to reassign elements:
 array[max_index] = last_negative;
    array[last_negative_index] = max;

**Comment by Kathrin-23** [comment]
I changed
