### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by DmitrTRC** [Kathrin-23/Work_2022_2#4]
https://github.com/Kathrin-23/Work_2022_2/blob/89a582d020776bec1ba1db08afb91599c41dd048/HW_4_1_b/main.cpp#L1

* Try to use simple logic

`for ( iterate over A ){
     bool is_found = false
     for ( iterate over B ){
     if ( A[I] = B[j] ){
          is_found = true
          break;
         }
  if ( is_found) printf( I )  
}
}
`

**Comment by Kathrin-23** [comment]
на iterate over - ругался, программа сравнивает только с одним элементом из массива В
